import requests
import xarray as xr
import pandas as pd
import scipy
import numpy as np
from roaring_landmask import RoaringLandmask
import matplotlib.pyplot as plt
import logging
from pathlib import Path
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import re

logging.basicConfig(filename='utils.log', encoding='utf-8', level=logging.INFO)
logger = logging.getLogger(__name__)


def get_future_intensity(link, current_timestep = 'f006', future_timestep = 'f030'):
    
    atm_args = dict(typeOfKey = 'isobaricInhPa',filename="Model_Data/temp_gribs/atm_temp.grb2" )
    sfc_args = dict(typeOfKey = 'meanSea',filename="Model_Data/temp_gribs/sfc_temp.grb2")
    
    

    
    
    print(f'Getting future intensities on link {link}')

    link = re.sub(current_timestep, future_timestep, link)
    

    sfc_df = download_and_open(link, **sfc_args)

    sfc_center = get_sfc_center(sfc_df, next_step = True)

    if not sfc_center:
        return {'24hr Minimum Central Pressure': np.nan, '24hr Max Winds': np.nan}
    
    
        
    atm_df = download_and_open(link, **atm_args)
    sfc_layer = atm_df.sel(isobaricInhPa = sfc_center['mslp'], method = 'nearest')

    max_wind = np.nanmax(np.sqrt(sfc_layer['u'].values**2 + sfc_layer['v'].values**2))
    

    return {'24hr Minimum Central Pressure': sfc_center['mslp'], '24hr Max Winds': max_wind}

def consolidate_data(data_path):

    '''
        Takes a list of separate Netcdf files generated from the Dataset creator and consolidates them.
        Assumes the netcdfs have 50 frames per file.
    '''    

    directory_path = Path(data_path)
    files_only = [data_path + '/' + entry.name for entry in directory_path.iterdir() if entry.is_file() and entry.name != '.gitkeep']
    ds_started = False
    starting_num = 0
    for file in files_only:
        print(file)
        
        if not ds_started:
            ds = xr.open_dataset(file)
            num_frames = len(ds['frame_link'].values)
            print(f'{num_frames} in {file}.')
            ds = ds.assign_coords(frame_number = ('valid_time',np.arange(starting_num, starting_num + num_frames, 1)))
            ds = ds.swap_dims({'valid_time':'frame_number'})
            starting_num = starting_num + num_frames
            ds_started = True
        else:
            ds_temp = xr.open_dataset(file)
            num_frames = len(ds_temp['frame_link'].values)
            print(f'{num_frames} in {file}.')
            ds_temp = ds_temp.assign_coords(frame_number = ('valid_time',np.arange(starting_num, starting_num + num_frames, 1)))
            starting_num = starting_num + num_frames
            ds_temp = ds_temp.swap_dims({'valid_time':'frame_number'})
            ds = xr.concat([ds, ds_temp], dim = 'frame_number')

            
    return ds

def download_and_open(url, typeOfKey = 'isobaricInhPa', filename="temp.grib2"):

  ## url: web link to AWS bucket file
  ## typeofKey: One of either 'isobaricInhPa' or 'meanSea'
  ## filename: name of temporary file


  print("Downloading filtered data...")
  response = requests.get(url, stream=True)
  response.raise_for_status()

  with open(filename, 'wb') as f:
    for chunk in response.iter_content(chunk_size=8192):
      f.write(chunk)

      # 3. Open with xarray using the cfgrib engine
  ds = xr.open_dataset(filename, 
                       filter_by_keys={'typeOfLevel': typeOfKey },
                       engine='cfgrib')
  return ds  

def random_link_selection(num_of_frames, used_links, links_path):
    
    ## num_of_frames: the number of random frames you want to select
    ## links_path: the local path to where the link_list txt file is located
    ##             link_list.txt is generated by the ListingFiles.ipynb

    result = []
    with open(links_path) as f:
        links = pd.read_csv(f)
    available_links = links[~links.isin(used_links)]
    random_frames = available_links.sample(num_of_frames)
    for link in random_frames.values:
        result.append('https://noaa-nws-hafs-pds.s3.amazonaws.com/' + link)
    
    return np.squeeze(result)

def get_sfc_center(ds, next_step = False):

    if ds['prmsl'].min().values > 10000:
       ds['prmsl'] = ds['prmsl']/100
    min_pressure = ds['prmsl'].min().values
    if min_pressure > 1005 and not next_step: # Pressure threshold (pa) 1005mb, I don't care about the threshold for just getting the storm center at the next step
        print(f'{np.round(min_pressure, decimals =2)}mb is above the pressure threshold of 1005mb')
        logger.info(f'{np.round(min_pressure, decimals =2)}mb is above the pressure threshold of 1005mb')
        return None
    else:
        print(f'{np.round(min_pressure, decimals = 2)}mb is below the pressure threshold of 1005mb')
    
    nan_mask = ds['prmsl'].isnull()
    ds_sfc = ds.where(~nan_mask, drop = True).isel(latitude = slice(50,-50), longitude = slice(50,-50))

    slp_threshold = np.quantile(ds_sfc['prmsl'], 0.01)
    slp_clusters = ds_sfc['prmsl'].where(ds_sfc['prmsl'] < slp_threshold)
    slp_clusters_mask = ~slp_clusters.isnull()

    clusters = scipy.ndimage.label(slp_clusters_mask)
    cluster_size = []
    for a in np.arange(clusters[1]):
        cluster_number = a + 1
        cluster_size.append(np.sum(np.where(clusters[0] == cluster_number, 1, 0)))
    try:
        largest_cluster_id = np.argmax(cluster_size) + 1
    except Exception as e:
        return None
    largest_cluster = xr.where(clusters[0] == largest_cluster_id, ds_sfc['prmsl'], 0)
    center_y, center_x = scipy.ndimage.center_of_mass(largest_cluster.values)
    largest_cluster_outline = np.where(clusters[0] == largest_cluster_id, True, False)
    mslp = ds_sfc['prmsl'].where(clusters[0] == largest_cluster_id).min().values

    center_lat =  ds_sfc.latitude.isel(latitude = int(np.round(center_y)))
    center_lon =  ds_sfc.longitude.isel(longitude =int(np.round(center_x)))

    storm_region = ds.sel(latitude = slice(center_lat.values -2, center_lat.values + 2), longitude = slice(center_lon.values -2, center_lon.values + 2))
    if storm_region['prmsl'].isnull().any():
        print('NaNs in storm region, skipping frame.')
        logger.info('NaNs in surface storm region, skipping frame.')
        return None

    l = RoaringLandmask.new()
    lon_mesh, lat_mesh = np.meshgrid(storm_region.longitude.values, storm_region.latitude.values)
    on_land = l.contains_many(lon_mesh.ravel(), lat_mesh.ravel())



    if np.any(on_land) and not next_step:
       print('Inner nest contains land.')
       logger.info('Inner nest contains land.')
       return None
    
    
    center_info = dict(center_lat = center_lat, center_lon = center_lon, mslp = mslp)
    return center_info 
# Extra return valueslargest_cluster_outline, ds_sfc.latitude.values, ds_sfc.longitude.values

def plot_polar(ds):
    fig, ax = plt.subplots(nrows= 1, ncols=1, figsize=(8, 8),subplot_kw={'projection': 'polar'})

    angle, radius = ds.angle.values, ds.radius.values

    Theta, R = np.meshgrid(angle, radius)


    ax.pcolor(Theta, R, ds.values[1:,1:])
    plt.show()

def plot_polar_from_arrays(radius, angle, values):
    
    fig, ax = plt.subplots(nrows= 1, ncols=1, figsize=(8, 8),subplot_kw={'projection': 'polar'})
    R, Theta = np.meshgrid(radius, angle)
    ax.pcolormesh(R, Theta, values)
    fig.colorbar()
    plt.show()

def standard_data_normalizer(da):
    frame_number, angle, radius = da.shape
    flattened_arrary = da.values.reshape(-1,1)
    scaler = StandardScaler()
    data_normalized_flat = scaler.fit_transform(flattened_arrary)
    data_normalized = data_normalized_flat.reshape(frame_number, angle, radius)

    return data_normalized

def minmax_data_normalizer(da):
    frame_number, angle, radius = da.shape
    flattened_arrary = da.values.reshape(-1,1)
    scaler = MinMaxScaler()
    data_normalized_flat = scaler.fit_transform(flattened_arrary)
    data_normalized = data_normalized_flat.reshape(frame_number, angle, radius)

    return data_normalized