import requests
import xarray as xr
import pandas as pd
import scipy
import numpy as np


def download_and_open(url, typeOfKey = 'isobaricInhPa', filename="temp.grib2"):

  ## url: web link to AWS bucket file
  ## typeofKey: One of either 'isobaricInhPa' or 'meanSea'
  ## filename: name of temporary file


  print("Downloading filtered data...")
  response = requests.get(url, stream=True)
  response.raise_for_status()

  with open(filename, 'wb') as f:
    for chunk in response.iter_content(chunk_size=8192):
      f.write(chunk)

      # 3. Open with xarray using the cfgrib engine
  ds = xr.open_dataset(filename, 
                       filter_by_keys={'typeOfLevel': typeOfKey },
                       engine='cfgrib')
  return ds  

def random_link_selection(num_of_frames, links_path):
    
    ## num_of_frames: the number of random frames you want to select
    ## links_path: the local path to where the link_list txt file is located
    ##             link_list.txt is generated by the ListingFiles.ipynb

    result = []
    with open(links_path) as f:
        links = pd.read_csv(f)
    random_frames = links.sample(num_of_frames)
    for link in random_frames.values:
        result.append('https://noaa-nws-hafs-pds.s3.amazonaws.com/' + link)
    
    return result

def get_sfc_center(ds):

    if ds['prmsl'].min().values > 10000:
       ds['prmsl'] = ds['prmsl']/100
    min_pressure = ds['prmsl'].min().values
    if min_pressure > 1005: # Pressure threshold (pa) 1005mb
        print(f'{np.round(min_pressure, decimals =2)}mb is above the pressure threshold of 1005mb')
        return None, None, None, None
    else:
        print(f'{np.round(min_pressure, decimals = 2)}mb is below the pressure threshold of 1005mb')
    nan_mask = ds['prmsl'].isnull()
    ds_sfc = ds.where(~nan_mask, drop = True).isel(latitude = slice(50,-50), longitude = slice(50,-50))
    

    slp_threshold = np.quantile(ds_sfc['prmsl'], 0.01)
    slp_clusters = ds_sfc['prmsl'].where(ds_sfc['prmsl'] < slp_threshold)
    slp_clusters_mask = ~slp_clusters.isnull()

    clusters = scipy.ndimage.label(slp_clusters_mask)
    cluster_size = []
    for a in np.arange(clusters[1]):
        cluster_number = a + 1
        cluster_size.append(np.sum(np.where(clusters[0] == cluster_number, 1, 0)))

    
    largest_cluster_id = np.argmax(cluster_size) + 1
    largest_cluster = xr.where(clusters[0] == largest_cluster_id, ds_sfc['prmsl'], 0)
    center_y, center_x = scipy.ndimage.center_of_mass(largest_cluster.values)
    largest_cluster_outline = np.where(clusters[0] == largest_cluster_id, True, False)
    mslp = ds_sfc['prmsl'].where(clusters[0] == largest_cluster_id).min().values

    center_lat =  ds_sfc.latitude.isel(latitude = int(np.round(center_y)))
    center_lon =  ds_sfc.longitude.isel(longitude =int(np.round(center_x)))
    
    center_info = dict(center_lat = center_lat, center_lon = center_lon, mslp = mslp)
    return center_info, largest_cluster_outline, ds_sfc.latitude.values, ds_sfc.longitude.values